myanimeproject/anime/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'anime'


urlpatterns = [
    path('', views.home, name='home'),
    path('all_anime', views.all_anime, name='all_anime'),
    path('search/', views.search_results, name='search_results'),
    path('add/', views.add_anime, name='add'),
    path('detailed_anime/<str:id>/', views.detailed_anime, name='detailed_anime'),
    path('detailed_anime/<str:anime_id>/season/<str:season_id>/episode/<str:episode_id>/', views.episode_detail, name='episode_detail'),
    path('get_episodes/<int:anime_id>/season/<int:season_id>/', views.get_episodes, name='get_episodes'),
    path('delete_anime/<str:id>/', views.delete_anime, name='delete_anime'),
    path('delete_comment/<str:comment_id>/', views.delete_comment, name='delete_comment'),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myanimeproject/api/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'api'


urlpatterns = [
    path('', views.get_routes),
    path('animes/', views.get_animes),
    path('anime/<str:id>', views.get_anime)
    

]

myanimeproject/myanimeproject/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime.urls', namespace='anime')),
    path('', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
]

myanimeproject/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'users'


urlpatterns = [
    path('add_to_watchlist/<str:id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('delete_from_watchlist/<str:id>/', views.delete_from_watchlist, name='delete_from_watchlist'),
    path('profile/<str:pk>/', views.profile, name='profile'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('register/', views.register_page, name='register'),
    path('update_profile/', views.update_profile, name='update_profile'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myanimeproject/anime/models.py
from django.db import models
from users.models import User

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=100)
    

    def __str__(self):
        return self.name



class LanguageOption(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name



class Anime(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    genres = models.ManyToManyField(Genre)
    release_date = models.DateField()
    status = models.CharField(max_length=50)
    rating = models.DecimalField(max_digits=3, decimal_places=2)
    cover_image = models.ImageField(null=True, blank=True, upload_to='anime_cover_img/')
    subtitle_or_dub = models.ManyToManyField(LanguageOption, related_name='animes')

    class Meta:
        ordering = ['title']


    def __str__(self):
        return self.title
    

    def total_seasons(self):
        return self.seasons.count()

    def total_episodes(self):
        return sum(season.episodes.count() for season in self.seasons.all())
    


class Season(models.Model):
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, related_name='seasons')
    season_number = models.PositiveIntegerField()
    release_date = models.DateField()

    def __str__(self):
        return f"{self.anime.title} - Season {self.season_number}"



class Episode(models.Model):
    season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name='episodes')
    title = models.CharField(max_length=200)
    episode_number = models.PositiveIntegerField()
    summary = models.TextField()
    air_date = models.DateField()
    duration = models.DurationField()
    video_file = models.FileField(upload_to='anime_videos/')
    episod_cover_image = models.ImageField(null=True, blank=True, upload_to='episode_cover_img/')
    

    def __str__(self):
        return f"{self.season.anime.title} - Season {self.season.season_number} - Episode {self.episode_number}"
    





class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.body

myanimeproject/anime/forms.py
from .models import Anime
from django.forms import ModelForm

        
        
class AnimeAddForm(ModelForm):
    class Meta:
        model = Anime
        fields = '__all__'

myanimeproject/anime/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Anime, Genre, LanguageOption, Episode, Season, Comment
from users.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import AnimeAddForm
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.paginator import Paginator





def home(request):
    anime_list = Anime.objects.all()
    genres = Genre.objects.all()
    popular_animes = Anime.objects.filter(rating__gte=4.5)  # Adjust the rating threshold as needed
    heading = "Most Popular"
    context = {'anime_list': anime_list, 'genres': genres, 'heading':heading, 'popular_animes': popular_animes}
    return render(request, 'anime/home.html', context)



def search_results(request):
    query = request.GET.get("query")
    genres = Genre.objects.all()
    genre_name = request.GET.get("genre")
    
    if query:
        anime_list = Anime.objects.filter(Q(title__icontains=query) | Q(description__icontains=query) | Q(genres__name__icontains=query))
        anime_list = list(set(anime_list))
    elif genre_name:
        anime_list = Anime.objects.filter(genres__name=genre_name)
    else:
        anime_list = Anime.objects.all()


    paginator = Paginator(anime_list, 4)
    page_number = request.GET.get('page')
    anime_list = paginator.get_page(page_number)

    heading = "Search results"
    context = {'anime_list': anime_list, 'genres': genres, 'heading': heading}

    return render(request, 'anime/search_results.html', context)



def all_anime(request):
    anime_list = Anime.objects.all()
    genres = Genre.objects.all()

    paginator = Paginator(anime_list, 6)
    page_number = request.GET.get('page')
    anime_list = paginator.get_page(page_number)

    heading = "All Anime"
    context = {'anime_list': anime_list, 'heading': heading, 'genres': genres}

    return render(request, 'anime/all_anime.html', context)



@login_required(login_url='login')
def delete_anime(request, id):
    anime = Anime.objects.get(id=id)
    
    if request.method == "POST":
        anime.cover_image.delete()
        anime.delete()
        return redirect('anime:home')
    return render(request, 'anime/delete_confirm.html', {'obj': anime})



@login_required(login_url='login')
def add_anime(request):
    form = AnimeAddForm()
    genres = Genre.objects.all()
    subtitle_or_dub = LanguageOption.objects.all()

    if request.method == 'POST':
        anime_genre = request.POST.get('genre')
        anime_languageoption = request.POST.get('subtitle-or-dub')

        genre, created = Genre.objects.get_or_create(name=anime_genre)
        languageoption, created = LanguageOption.objects.get_or_create(name=anime_languageoption)

        form = AnimeAddForm(request.POST)

        new_anime = Anime(cover_image=request.FILES['cover_image'], title=form.data['title'], 
                          description=form.data['description'], 
                          release_date=form.data['release_date'], status=form.data['status'], 
                          rating=form.data['rating'])
        
        new_anime.save()
        new_anime.genres.add(genre)
        new_anime.subtitle_or_dub.add(languageoption)

        return redirect('anime:home')
    
    context = {'form': form, 'genres': genres, 'subtitle_or_dub': subtitle_or_dub}
    return render(request, 'anime/add_anime.html', context)



def detailed_anime(request, id, season_id=None):
    genres = Genre.objects.all()
    anime = Anime.objects.get(id=id)
    seasons = anime.seasons.all()
    anime_comments = anime.comment_set.all().order_by('-created')

    if season_id:
        season = get_object_or_404(Season, id=season_id, anime=anime)
    else:
        season = seasons.first()

    
    if request.method == "POST":
        comment = Comment.objects.create(
            user = request.user,
            anime = anime,
            body = request.POST.get('body')
        )
        return redirect('anime:detailed_anime', id=id)  # Redirect after POST


    context = {'anime': anime, 'seasons': seasons, 'season': season, 'comments': anime_comments, 'genres': genres}
    return render(request, 'anime/detailed_anime.html', context)


def episode_detail(request, anime_id, season_id, episode_id):
    genres = Genre.objects.all()
    anime = get_object_or_404(Anime, id=anime_id)
    season = get_object_or_404(Season, id=season_id, anime=anime)
    episode = get_object_or_404(Episode, id=episode_id, season=season)
    seasons = anime.seasons.all()

    context = {'anime': anime, 'season': season, 'episode':episode, 'seasons': seasons, 'genres':genres}
    return render(request, 'anime/episode_detail.html', context)



@login_required(login_url='login')
def delete_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    anime = comment.anime
    
    if request.method == 'POST':
        comment.delete()
        return redirect('anime:detailed_anime', anime.id)
    return render(request, 'anime/delete_confirm.html', {'obj': comment})



def get_episodes(request, anime_id, season_id):
    anime = get_object_or_404(Anime, id=anime_id)
    season = get_object_or_404(Season, id=season_id, anime=anime)
    episodes = season.episodes.all()

    html = render_to_string('anime/episode_list.html', {'episodes': episodes})
    return JsonResponse({'html': html})

myanimeproject/anime/templates/anime/add_anime.html
{% extends 'base.html'%}
{% load widget_tweaks %}

{% block title %} login_register page {% endblock %}


{% block content %}

        <div class="container mt-5">
            <div class="card" style="background-color: rgba(0, 0, 0, 0.932); border-radius: 0; padding: 5%; margin: 9.375rem 0 6.25rem; color: #ffffff;">
            
                    {% if user.is_authenticated%}
                    <h1 style="margin-bottom: 30px;">Add Anime</h1>
                    <form method="post" id="itemForm" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <div>
                            <label>Anime Cover</label>
                            {{ form.cover_image|add_class:"form-control form-control1" }}
                        </div>
                        <div class="mt-3">
                            <label>Title:</label>
                            {{ form.title|add_class:"form-control form-control1"|attr:"placeholder:Title" }}
                        </div>
                        <div class="mt-3">
                            <label>Description:</label>
                            {{ form.description|add_class:"form-control form-control1"|attr:"placeholder:Description" }}
                        </div>
                        <div class="mt-3">
                            <label for="anime_genre">Genre:</label>
                            <input required type="text" name="genre" list="genre-list" class="form-control form-control1" >
                            <datalist id="genre-list">
                                {% for genre in genres %}
                                    <select id="anime_genre">
                                        <option value="{{ genre.name }}" >{{ genre.name }}</option>
                                    </select>
                                {% endfor %}
                            </datalist>
                        </div>
                        <div class="mt-3">
                            <label>Release date:</label>
                            <input required type="date" name="release_date" class="form-control form-control1">
                        </div>
                        <div class="mt-3">
                            <label>Status:</label>
                            {{ form.status|add_class:"form-control form-control1"|attr:"placeholder:Status" }}
                        </div>
                        <div class="mt-3">
                            <label>Rating:</label>
                            <input required type="number" step="0.01" name="rating" class="form-control form-control1">
                        </div>
                        <div class="mt-3">
                            <label for="anime_genre">Language option:</label>
                            <input required type="text" name="subtitle-or-dub" list="subtitle-or-dub-list" class="form-control form-control1" >
                            <datalist id="subtitle-or-dub-list">
                                {% for option in subtitle_or_dub %}
                                    <select id="subtitle-or-dub">
                                        <option value="{{ option.name }}" >{{ option.name }}</option>
                                    </select>
                                {% endfor %}
                            </datalist>
                        </div>

                        <button type="submit" class="btn btn-danger py-2 login-btn" id="liveToastBtn" style="border-radius: 0; width: 30%;" >Add</button>
                    </form>
                    
                {% else %}
                    <h2>You don't have a permission to add event</h2>

                {% endif %}

            </div>
        </div>
    
    
        
{% endblock %}

myanimeproject/anime/templates/anime/animes.html
<div class="container">

    <!-- <h2 style="margin-top: 120px;"> {{ heading }}</h2> -->
    <!-- <hr style="color: rgba(255, 255, 255, 0.568);"> -->

    <div class="row row-cols-1 row-cols-md-4 g-4">
    {% if anime_list %}
        {% for anime in anime_list %}
            <div class="col mt-5">
                <div class="card h-100" style="background-color: transparent;">
                    <a href="#">
                        <img src="{{ anime.cover_image.url }}" class="card-img-top img-hover" alt="{{ anime.title }}">
                    </a>

                    <div class="overlay">
                        <div class="card-btn-box">
                            <a href="{% url 'anime:detailed_anime' anime.id %}">
                                <img class="video-btn"  src="/media/icons/play.svg">
                            </a>
                            {% if anime in request.user.animes.all %}
                                <a href="{% url 'users:delete_from_watchlist' anime.id %}"> 
                                    <img class="watchlist-delete-btn" src="/media/icons/x-lg.svg">
                                </a>
                            {% else %}
                                <a href="{% url 'users:add_to_watchlist' anime.id %}"> 
                                    <img class="bookmark-btn" src="/media/icons/plus-lg.svg">
                                </a>
                            {% endif %}
                            {% if request.user.is_authenticated and request.user.is_superuser %}
                                <a href="{% url 'anime:delete_anime' anime.id %}"> 
                                    <img class="delete-anime-btn" src="/media/icons/trash3.svg">
                                </a>   
                            {% endif %}
                            
                        </div>
                    </div>

                    <div class="card-body">
                        <h6 class="card-title">{{ anime.title }}</h6>
                        {% for language in anime.subtitle_or_dub.all %}
                            <small class="card-text" style="color: #f47521">{{ language.name }} |</small>
                        {% endfor %}
                        
                        <p class="card-text mb-2">{{ anime.description |slice:":60" }}</p>
                        <small class="card-text">Seasons: {{ anime.total_seasons }}</small>
                        <br>
                        <small class="card-text">Episodes: {{ anime.total_episodes }}</small>
                        <br>
                        <small class="card-text">☆ {{ anime.rating }}</small>
                    </div>            
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3 style="margin-top: 120px; color: white; text-align: center;">No anime data available</h3>
    {% endif %}
    </div>
</div>

myanimeproject/anime/templates/anime/detailed_anime.html
{% extends 'base.html'%}

{% block title %} Profile {% endblock %}

{% block content %}

    <main>
        <div class="img-box">
            <img src="{{ anime.cover_image.url }}" class="detailed-anime-background" alt="{{ anime.title }}">
            <img src="{{ anime.cover_image.url }}" class="detailed-anime-cover" alt="{{ anime.title }}">
        </div>
        <div class="container mb-5">
        
            <div class="row align-items-md-stretch">
                <div class="col-md-7">
                    <div class="h-100 p-3" style="background-color: none;">
                        <h2>{{ anime.title }}</h2>
                        {% for language in anime.subtitle_or_dub.all %}
                            <small style="color: #f47521">{{ language.name }} |</small>
                        {% endfor %}
                        <div>
                            <small class="card-text">Average Rating: <span style="color: #41748d;">{{ anime.rating }}☆</span></small>
                            <p><small class="card-text">Status: {{ anime.status }} </small></p>
                            <small class="card-text">Seasons: {{ anime.total_seasons }}</small>
                            <p><small class="card-text">Episodes: {{ anime.total_episodes }}</small></p>
                        </div>
                        <p style="color:white;">{{ anime.description }}</p>
                        {% for genre in anime.genres.all %}
                            <div class="badge genre-badge">{{ genre.name }}</div>
                        {% endfor %}
                        <div>
                            
                            {% if anime in request.user.animes.all %}
                                <a href="{% url 'users:delete_from_watchlist' anime.id %}" class="btn add-watchlist-btn">
                                    <img class="delete-watchlist-icon" src="/media/icons/x-lg.svg">Delete from watchlist 
                                </a>
                            {% else %}
                                <a href="{% url 'users:add_to_watchlist' anime.id %}" class="btn add-watchlist-btn"> 
                                    <img class="add-watchlist-icon" src="/media/icons/plus-lg.svg">Add to watchlist
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="col-md-5">
                    <div class="h-100 p-5 ">
                            {% for season in seasons %}
                            {% if forloop.first %}
                                {% for episode in season.episodes.all %}
                                    {% if forloop.first %}
                                    <!-- Display the first episode image -->
                                        <div class="card" style="border-radius: 0; background-color: transparent; border: none;">
                                            <img  src="{{ episode.episod_cover_image.url }}" alt="{{ episod_cover_image.title }}" style="width: 100%; max-width: 400px;">
                                            <div>
                                                <a href="{% url 'anime:episode_detail' anime.id season.id episode.id %}" class="btn episode-play-btn"> 
                                                    <img class="btn-video-icon" src="/media/icons/play.svg">Start watching E1
                                                </a>
                                            </div>    
                                        </div> 
                                    {% endif %}  
                                {% endfor %}
                            {% endif %}
                            {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        
        <div class="container">
            <div class="card" style="background-color: rgba(0, 0, 0, 0.932); border-radius: 0; padding: 5%; margin: 6.25rem 0 6.25rem; color: #ffffff;">
                <h3 style="margin-bottom: 30px;">Comments</h3>
                {% if user.is_authenticated %}
                <div class="card mb-5">
                    <form method="POST", action="">
                        {% csrf_token %}

                        <div class="form-floating">
                            <textarea name="body" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
                            <label for="floatingTextarea2">Leave a comment here</label>
                        </div>
                        
                        <button type="submit" class="btn btn-primary comment-btn m-3" id="liveToastBtn" >Post</button>
                    </form>  
                </div>
                {% endif %}
                {% for comment in comments %}
                    <div class="card text-bg-dark mb-3 p-3">
                        <div class="row g-0">
                            <div class="col-md-1">
                                <a href="{% url 'users:profile' comment.user.id %}">
                                    <img src="{{ comment.user.avatar.url }}" style="border-radius: 50%; width: 60px; height: 60px;"/>
                                </a>
                            </div>
                            <div class="col-md-10">
                                <p style="margin-bottom: 5px; color: #f47521;">{{comment.user.username}}</p>
                                <p style="margin: 0;">{{ comment.body }}</p>
                                <p style="margin: 0;"><small class="card-text" >{{ comment.created | timesince }} ago</small></p>
                                
                            </div>
                            <div class="col-md-1" data-bs-theme="dark">
                                {% if request.user == comment.user %}
                                    <a href="{% url 'anime:delete_comment' comment.id %}">
                                        <button type="button" class="btn-close" aria-label="Close"></button>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div> 
        </div>
    </main>



  {% endblock %}

myanimeproject/anime/templates/anime/episode_list.html
<div class="card text-bg-dark mb-3 dropdown-scroll" >
    {% for episode in episodes %}
    <a href="{% url 'anime:episode_detail' episode.season.anime.id episode.season.id episode.id %}" style="text-decoration: none;">

        <div class="row g-0 mb-2 episode-list-card">
            <div class="col-md-4">   
                <img class="img-fluid" src="{{ episode.episod_cover_image.url }}" alt="{{ episode.title }}" style="width: 100%; max-width: 400px;">    
            </div>
        
            <div class="col-md-8">
                <div>
                    <h6 class="episod-title-in-list">{{ episode.title }}</h6>
                    <p class="card-text"><small style="margin-left: 10px;">{{ episode.duration}}</small></p>
                </div>
            </div>
     
        </div>
    </a> 
    {% endfor %}
</div>

myanimeproject/anime/templates/anime/home.html
{% extends 'base.html' %}


{% block title %} Home {% endblock %}


{% block content %}
    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
          <div class="carousel-item active position-relative" data-bs-interval="2000">
              <img src="/media/anime_cover_img/f059202d-3d1d-4db4-aa0a-4531473091c01.png" class="d-block w-100" alt="...">
              <div class="myclass position-absolute">
                  <img src="/media/anime_cover_img/0f123b10-1e36-47ad-91ae-46dc0f0e2761.webp" alt="logo img" class="titan-logo">
                  <p class="text">Known in Japan as Shingeki no Kyojin, many years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land...</p>
                  <a href="{%  url 'anime:detailed_anime' 6%}"><button class="btn-1">Start Watching</button></a>
              </div>
          </div>
          <div class="carousel-item position-relative" data-bs-interval="2000">
              <img src="/media/anime_cover_img/ab8d4019-5254-418a-b450-534a9a8d4e0c.webp" class="d-block w-100" alt="...">
              <div class="myclass position-absolute">
                  <img src="/media/anime_cover_img/3de5c3ff-547a-40ec-a9b0-40f4113569ce.webp" alt="logo img" class="titan-logo">
                  <p class="text">The ultimate battle royale for divinity has begun. High schoolers must use their unique powers to compete against each other for the coveted title “God.” But as each brawl becomes more vicious than the last,...</p>
                  <a href="{%  url 'anime:detailed_anime' 5%}"><button class="btn-1">Start Watching</button></a>
              </div>
          </div>
          <div class="carousel-item position-relative">
              <img src="/media/anime_cover_img/20e89e1d-4420-4113-b7ec-d828255c0ef12.png" class="d-block w-100" alt="...">
              <div class="myclass position-absolute">
                  <img src="/media/anime_cover_img/1bdf4f33-6205-4ac0-9cd7-b2b01d6342cd.webp" alt="logo img" class="titan-logo-2">
                  <p class="text">After finally adopting a child, the Sonoyamas were unprepared for the mystery that would soon unravel. Hitori seems to be the perfect son for his loving parents. He's handsome, intelligent, and grateful for his...</p>
                  <a href="{%  url 'anime:detailed_anime' 7%}"><button class="btn-1">Start Watching</button></a>
              </div>
          </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
      </button>
    </div>
    
    <div class="container">
        <h2 style="margin-top: 120px; color: white;"> {{ heading }}</h2>
       
    </div>
        
    <div class="container ">
            <div class="row row-cols-1 row-cols-md-4 g-4 mt-4">
            {% if popular_animes %}
                {% for anime in popular_animes|slice:":4" %}
                    <div class="col">
                        <div class="card h-100" style="background-color: transparent;">
                            <a href="#">
                                <img src="{{ anime.cover_image.url }}" class="card-img-top img-hover" alt="{{ anime.title }}">
                            </a>

                            <div class="overlay">
                                <div class="card-btn-box">
                                    <a href="{% url 'anime:detailed_anime' anime.id %}">
                                        <img class="video-btn"  src="/media/icons/play.svg">
                                    </a>
                                    {% if anime in request.user.animes.all %}
                                        <a href="{% url 'users:delete_from_watchlist' anime.id %}"> 
                                            <img class="watchlist-delete-btn" src="/media/icons/x-lg.svg">
                                        </a>
                                    {% else %}
                                        <a href="{% url 'users:add_to_watchlist' anime.id %}"> 
                                            <img class="bookmark-btn" src="/media/icons/plus-lg.svg">
                                        </a>
                                    {% endif %}
                                    {% if request.user.is_authenticated and request.user.is_superuser %}
                                        <a href="{% url 'anime:delete_anime' anime.id %}"> 
                                            <img class="delete-anime-btn" src="/media/icons/trash3.svg">
                                        </a>   
                                    {% endif %}
                                    
                                </div>
                            </div>

                            <div class="card-body">
                                <h6 class="card-title">{{ anime.title }}</h6>
                                {% for language in anime.subtitle_or_dub.all %}
                                    <small class="card-text" style="color: #f47521">{{ language.name }} |</small>
                                {% endfor %}
                                
                                <small class="card-text">☆ {{ anime.rating }}</small>
                            </div>            
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h3 style="margin-top: 120px; color: white; text-align: center;">No anime data available</h3>
            {% endif %}
            </div>
        </div>
    
    <div>
        <a href="{% url 'anime:detailed_anime' 6 %}">
            <img class="my-img" src="/media/anime_cover_img/4cf2741f-e4d3-45fb-8621-5b4ab5a9e23f.png">
        </a>
    </div>

    <div style="display: flex; justify-content: center; align-items: center; flex-direction: column;">
        
        <img src="/media/icons/yuzu.png" />
        
        <p class="text" style="text-align: center; margin: 15px 0 25px;">Still looking for something to watch? <br>
                Check out our full library</p>
        <a class="all-btn" href="{% url 'anime:all_anime' %}" style="margin-bottom: 50px;">View all</a>
    </div>
{% endblock %}

    