myanimeproject/api/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'api'


urlpatterns = [
    path('', views.get_routes),
    path('animes/', views.get_animes),
    path('anime/<str:id>', views.get_anime)
    

]

myanimeproject/myanimeproject/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime.urls', namespace='anime')),
    path('', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
]

myanimeproject/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'users'


urlpatterns = [
    path('add_to_watchlist/<str:id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('delete_from_watchlist/<str:id>/', views.delete_from_watchlist, name='delete_from_watchlist'),
    path('profile/<str:pk>/', views.profile, name='profile'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('register/', views.register_page, name='register'),
    path('update_profile/', views.update_profile, name='update_profile'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myanimeproject/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.



class User(AbstractUser):
    animes = models.ManyToManyField('anime.Anime', blank=True, related_name='users')
    bio = models.TextField(null=True)
    avatar = models.ImageField(null=True, default='blank-profile-picture-973460_1280.png', upload_to='profile_img/')

myanimeproject/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.forms import ModelForm
from django import forms



class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

        

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'username', 'bio', 'email']

myanimeproject/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from anime.models import Anime, Genre
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import MyUserCreationForm, UserForm
from django.contrib import messages




@login_required(login_url='login')
def profile(request, pk):
    user = User.objects.get(id=int(pk))
    query = request.GET.get("query")
    genres = Genre.objects.all()

    if query:
        animes = user.animes.filter(Q(title__icontains=query) | Q(description__icontains=query) | Q(genres__name__icontains=query))
        animes= list(set(animes))
    else:
        animes = user.animes.all()
        
    context = {'anime_list': animes, 'user': user, 'genres': genres}
    return render(request, 'users/profile.html', context)



@login_required(login_url='login')
def add_to_watchlist(request, id):
    anime = Anime.objects.get(id=id)
    user = request.user
    user.animes.add(anime)
    return redirect('users:profile', user.id)



@login_required(login_url='login')
def delete_from_watchlist(request, id):
    anime = Anime.objects.get(id=id)

    if request.method == "POST":
        request.user.animes.remove(anime)
        return redirect('users:profile', request.user.id)
    
    return render(request, 'users/delete_confirm.html', {'obj': anime})




def login_page(request):
    genres = Genre.objects.all()
    page = 'login'

    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == "POST":
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "Username doesn't exist!")
            return redirect('users:login')


        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('anime:home')
        else:
            messages.error(request, "Username or password is incorrect!")

    context = {'page': page, 'genres': genres}
    return render(request, 'users/login_register.html', context)




def logout_page(request):
    logout(request)
    return redirect('users:login')



def register_page(request):
    genres = Genre.objects.all()
    form = MyUserCreationForm()

    if request.method == "POST":
        form = MyUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('anime:home')

    context = {'form': form, 'genres': genres}
    return render(request, 'users/login_register.html', context)



@login_required(login_url='login')
def update_profile(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users:profile', user.id)
    return render(request, 'users/update_profile.html', {'form': form})

myanimeproject/users/templates/users/delete_confirm.html
{% extends 'base.html'%}

{% block title %} Delete page {% endblock %}


{% block content %}
    <div class="container mt-5">
        <form method="POST", action="">
            {% csrf_token %}
            <h3 style="margin-top: 120px; color: white;">Are you sure you want to delete "{{ obj }}"?</h3>
            <input type="submit" value="Delete" class="btn btn-danger">
            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary" >Cancel</a>

        </form>
    </div>

{% endblock %}

myanimeproject/users/templates/users/login_register.html
{% extends 'base.html'%}
{% load widget_tweaks %}

{% block title %} login_register page {% endblock %}


{% block content %}

    {% if page == 'login' %}
        <div class="position-absolute" style="margin-top: 30px;"><img src="/media/icons/register-hime.png" class="register-img"></div>
        <main class="form-signin m-auto d-flex justify-content-center" >
            
            <form method="POST" action="" class="login-register-form">
                {% csrf_token %}
                <div class="d-flex justify-content-center h1-container">
                    <h1 class="h4 mb-3 fw-normal">Log In</h1>
                </div>
                <div class="form-container">
                    
                    <div>
                        <label class="label-color">Username</label>
                        <input required type="text" name="username" class="form-control form-control1">
                    </div>
                    <div>
                        <label class="label-color">Password</label>
                        <input required type="password" name="password" class="form-control form-control1">
                        <a href="#" class="sign-link" >Forgot password?</a>
                    </div>
                    
                </div>
                <div class="d-flex justify-content-center" >
                    <button class="btn btn-danger py-2 login-btn" type="submit">LOG IN</button>
                </div>
                <div class="d-flex justify-content-center">
                    <p class="no-account">No account? </p>
                    <a href="{% url 'users:register' %}" class="sign-link">CREATE ONE</a>
                </div>    
            </form>    
        </main>

    {% else %}
    <div class="position-absolute" style="margin-top: 30px;"><img src="/media/icons/register-hime.png" class="register-img"></div>
        <main class="form-signin m-auto d-flex justify-content-center">
            
            <form method="POST" action="" class="login-register-form">
                {% csrf_token %}
                <div class="d-flex justify-content-center h1-container">
                    <h1 class="h4 mb-3 fw-normal">Create Account</h1>
                </div>
                <div class="form-container">
                    <div>
                        <label class="label-color">Username</label>
                        {{ form.username|add_class:"form-control form-control1"|attr:"placeholder:Username" }}
                    </div>
                    <div>
                        <label class="label-color">Password</label>
                        {{ form.password1|add_class:"form-control form-control1"|attr:"placeholder:Password" }}
                    </div>
                    <div>
                        <label class="label-color">Confirm Password</label>
                        {{ form.password2|add_class:"form-control form-control1"|attr:"placeholder:Confirm Password" }}
                    </div>

                </div>
            <div class="d-flex justify-content-center" >
                <button class="btn btn-danger py-2 login-btn" type="submit">CREATE ACCOUNT</button>
            </div>
            <div class="d-flex justify-content-center">
                <p class="no-account">Already have an account? </p>
                <a href="{% url 'users:login' %}" class="sign-link">Log in</a>
            </div>
            </form>   
        </main>
    {% endif %}
    
        
{% endblock %}

myanimeproject/users/templates/users/profile.html
{% extends 'base.html'%}

{% block title %} Profile {% endblock %}


{% block content %}
    <div class="profile-box">
        <div class="nav-item">
              <img src="{{ request.user.avatar.url }}" class="profile-avatar" />
        </div>

        <h1 style="margin-top: 20px; color: white;">{{user}}</h1>
        <p style="color: rgba(255, 255, 255, 0.568);">{{user.bio}}</p>
        <a href="{% url 'users:update_profile' %}" class="btn btn-danger login-btn" style="border-radius: 0; width: 20%; margin-top: 20px;">Update Profile</a>

    </div>



    <div class="container">
            
            <h2 style="margin-top: 120px; text-align: center;"> My animes </h2>
            <form class="d-flex mx-auto" style="width:50%;" role="search" action="{% url 'users:profile' user.id %}" method="GET" >
                <div class="input-group">
                <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="query" placeholder="Search your watchlist...">
                <button class="btn btn-outline-danger"  type="submit">Search</button>
                </div>
            </form>
            <hr style="color: rgba(255, 255, 255, 0.568);">
            
    </div>  

    {% if anime_list %}
        
        {% include 'anime/animes.html' %} 
            
    {% else %}
        
        <h3 style="margin-top: 70px; margin-bottom: 100px; color: white; text-align: center;">No anime found in your watchlist</h3>
        
    {% endif %}
    

        
{% endblock %}

myanimeproject/users/templates/users/update_profile.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block title %} Update profile page {% endblock %}




{% block content %}

        <div class="container mt-5">
            <div class="card" style="background-color: rgba(0, 0, 0, 0.932); border-radius: 0; padding: 5%; margin: 9.375rem 0 6.25rem; color: #ffffff;">
            
                {% if user.is_authenticated%}
                    <h1 style="margin-bottom: 30px;">Update profile</h1>
                    <form method="POST" action="" enctype="multipart/form-data" >
                        {% csrf_token %}
                        {{ form|crispy }}

                        <button type="submit" class="btn btn-danger py-2 mt-3" id="liveToastBtn" style="border-radius: 0; width: 30%;" >Update profile</button>
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success py-2 mt-3" style="border-radius: 0; width: 30%; margin-left: 10px;">Cancel</a>
                    </form>
                    
                {% else %}
                    <h2>You don't have a permission to update profile</h2>

                {% endif %}

            </div>
        </div>
    
    
        
{% endblock %}