myanimeproject/anime/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'anime'


urlpatterns = [
    path('', views.home, name='home'),
    path('all_anime', views.all_anime, name='all_anime'),
    path('search/', views.search_results, name='search_results'),
    path('add/', views.add_anime, name='add'),
    path('detailed_anime/<str:id>/', views.detailed_anime, name='detailed_anime'),
    path('detailed_anime/<str:anime_id>/season/<str:season_id>/episode/<str:episode_id>/', views.episode_detail, name='episode_detail'),
    path('get_episodes/<int:anime_id>/season/<int:season_id>/', views.get_episodes, name='get_episodes'),
    path('delete_anime/<str:id>/', views.delete_anime, name='delete_anime'),
    path('delete_comment/<str:comment_id>/', views.delete_comment, name='delete_comment'),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myanimeproject/api/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'api'


urlpatterns = [
    path('', views.get_routes),
    path('animes/', views.get_animes),
    path('anime/<str:id>', views.get_anime)
    

]

myanimeproject/myanimeproject/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime.urls', namespace='anime')),
    path('', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
]

myanimeproject/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'users'


urlpatterns = [
    path('add_to_watchlist/<str:id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('delete_from_watchlist/<str:id>/', views.delete_from_watchlist, name='delete_from_watchlist'),
    path('profile/<str:pk>/', views.profile, name='profile'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('register/', views.register_page, name='register'),
    path('update_profile/', views.update_profile, name='update_profile'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myanimeproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> 
    <title>{% block title%} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" >
    <link rel="stylesheet" href="{% static 'styles/register.css' %}" >
    <link rel="stylesheet" href="{% static 'styles/detailed_anime.css' %}" >
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>

    {% include 'nav.html' %}
    
   

    {% if messages %}
    <!-- Flexbox container for aligning the toasts -->
    <div aria-live="polite" aria-atomic="true" class="d-flex justify-content-center align-items-center w-100" style="margin-top: 180px; position: absolute; color:red;">
        <div class="toast-container position-fixed p-3" style="z-index: 1050;">
            {% for message in messages %}
            <div class="toast align-items-center text-bg-{{ message.tags }} border-0" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="5000">
                <div class="d-flex">
                    <div class="toast-body">
                        {{ message }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}


    {% block content%}

    {% endblock %}

    {% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script> -->

    <!-- Initialize toasts -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var toastElList = [].slice.call(document.querySelectorAll('.toast'))
            var toastList = toastElList.map(function (toastEl) {
                return new bootstrap.Toast(toastEl, { delay: 5000 })
            })
            toastList.forEach(toast => toast.show())
        });
    </script>
</body>
</html>

myanimeproject/templates/footer.html
    
    
  <footer class="py-3 my-4 mt-5">
    <ul class="nav justify-content-center pb-3 mb-4 position-relative" style="border-bottom: 1px solid #2b2b2b;">
      <li class="nav-item"><a href="{% url 'anime:home' %}" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="{% url 'anime:all_anime' %}" class="nav-link px-2 text-body-secondary">All</a></li>
      {% if request.user.is_authenticated %}
          <li class="nav-item mb-3"><a href="{% url 'users:profile' request.user.id %}" class="nav-link px-2 text-body-secondary">Profile</a></li>
          <li class="nav-item mb-3"><a href="{% url 'users:logout' %}" class="nav-link px-2 text-body-secondary">Log Out</a></li>    
      {% else %}
          <li class="nav-item mb-3"><a href="{% url 'users:login' %}" class="nav-link px-2 text-body-secondary">Profile</a></li>
          <li class="nav-item mb-3"><a href="{% url 'users:register' %}" class="nav-link px-2 text-body-secondary">Create Account</a></li>
          <li class="nav-item mb-3"><a href="{% url 'users:login' %}" class="nav-link px-2 text-body-secondary">Log In</a></li>
      {% endif %}

      <!-- Additional styling for the position of the Instagram icon -->
      <div class="position-absolute start-50 translate-middle-x" style="bottom: -20px;">
        <a href="https://www.instagram.com/a.r.myartwork/" class="nav-link px-2 text-body-secondary"><img src="/media/icons/icons8-instagram-24 (1).png" style="background-color: #181717;"></a>
      </div>
    </ul>
    <p class="text-center" style="color: #585858;">Anime</p>
  </footer>

myanimeproject/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top bg-dark" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'anime:home' %}">Anime</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex align-items-center" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'anime:home' %}">Home</a>
        </li>

        
        {% if request.user.is_authenticated and request.user.is_superuser%}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" href="#">
                User Menu
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'users:profile' request.user.id %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'anime:add' %}">Add new anime</a></li>
              </ul>
            </li>
            {% elif request.user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'users:profile' request.user.id %}">Profile</a>
              </li>

        {% endif %}

       
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" href="#">
            Genre
          </a>
          <ul class="dropdown-menu">
              <table class="table table-borderless table-sm">
                  <tbody>
                    <tr>
                      {% for genre in genres|slice:":3"%}
                      <td><a class="dropdown-item" href="{% url 'anime:search_results' %}?genre={{ genre.name }}">{{genre.name}}</a></td> 
                      {% endfor %}
                    </tr>
                    <tr>
                      {% for genre in genres|slice:"3:6"%}
                      <td><a class="dropdown-item" href="{% url 'anime:search_results' %}?genre={{ genre.name }}">{{genre.name}}</a></td> 
                      {% endfor %}
                    </tr>
                    <tr>
                      {% for genre in genres|slice:"6:9"%}
                      <td><a class="dropdown-item" href="{% url 'anime:search_results' %}?genre={{ genre.name }}">{{genre.name}}</a></td> 
                      {% endfor %}
                    </tr>
                    <tr>
                      
                      <td><a class="dropdown-item" href="{% url 'anime:search_results' %}">All</a></td>
                    </tr>
                    
                  </tbody>
              </table>     
          </ul> 
        </li>  
      </ul>
      
      <form class="d-flex mx-auto" role="search" action="{% url 'anime:search_results' %}" method="GET" >
          <div class="input-group">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="query" placeholder="Search">
            <button class="btn btn-outline-danger"  type="submit">Search</button>
          </div>
      </form>
      
      <div class="btn-group ms-auto">
        {% if request.user.is_authenticated %}
          
          <div class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'users:profile' request.user.id %}">
              <img src="{{ request.user.avatar.url }}" class="profile-icon" />
            </a>
          </div>
          <button type="button" class="btn btn-danger" style="border-radius: 5px;"><a href="{% url 'users:logout' %}" class="login-link">Log Out</a></button>
        {% else %}
          <button class="btn join-btn" type="submit"><a href="{% url 'users:register' %}" class="join-link">Join Now</a></button>
          <button type="button" class="btn btn-outline-danger"><a href="{% url 'users:login' %}" class="login-link">Log In</a></button>
        {% endif %}
      </div>
    </div>
  </div>
</nav>